export const toolboxConfig = {
  kind: "categoryToolbox",
  contents: [
    {
      kind: "category",
      name: "Movement",
      colour: "#00b894",
      contents: [
        { kind: "block", type: "mars_move_forward" },
        { kind: "block", type: "mars_move_forward_v" },
        { kind: "block", type: "mars_move_backward" },
        { kind: "block", type: "mars_move_backward_v" },
        { kind: "block", type: "mars_turn" },
        { kind: "block", type: "mars_turn_v" },
        { kind: "block", type: "mars_drive_meters" },
        { kind: "block", type: "mars_drive_meters_v" },
        { kind: "block", type: "mars_stop" },
        { kind: "block", type: "mars_set_speed" },
      ],
    },
    {
      kind: "category",
      name: "Navigation",
      colour: "#00cec9",
      contents: [
        { kind: "block", type: "mars_navigate_to" },
        { kind: "block", type: "mars_spin" },
        { kind: "block", type: "mars_save_position" },
        { kind: "block", type: "mars_go_to_position" },
        { kind: "block", type: "mars_drive_to" },
      ],
    },
    {
      kind: "category",
      name: "Arm & Gripper",
      colour: "#e17055",
      contents: [
        { kind: "block", type: "mars_arm_home" },
        { kind: "block", type: "mars_arm_move_to" },
        { kind: "block", type: "mars_arm_move_to_v" },
        { kind: "block", type: "mars_arm_move_to_g" },
        { kind: "block", type: "mars_arm_move_to_gv" },
        { kind: "block", type: "mars_gripper" },
        { kind: "block", type: "mars_wave" },
        { kind: "block", type: "mars_pick_up" },
        { kind: "block", type: "mars_joint_position" },
        { kind: "block", type: "mars_all_joints" },
        { kind: "block", type: "mars_arm_torque_off" },
        { kind: "block", type: "mars_arm_torque_on" },
      ],
    },
    {
      kind: "category",
      name: "Sensors",
      colour: "#0984e3",
      contents: [
        { kind: "block", type: "mars_get_distance" },
        { kind: "block", type: "mars_see_object" },
        { kind: "block", type: "mars_take_photo" },
        { kind: "block", type: "mars_get_object_position" },
        { kind: "block", type: "mars_tag_detect_arm" },
        { kind: "block", type: "mars_tag_detect_head" },
        { kind: "block", type: "mars_is_tag_detected_arm" },
        { kind: "block", type: "mars_is_tag_detected_head" },
        { kind: "block", type: "mars_get_angle_to_tag" },
        { kind: "block", type: "mars_get_battery" },
        { kind: "block", type: "mars_get_heading" },
        { kind: "label", text: "Store sensor values:" },
        { kind: "block", type: "mars_read_distance" },
        { kind: "block", type: "mars_read_heading" },
        { kind: "block", type: "mars_read_battery" },
        { kind: "block", type: "mars_read_tag" },
      ],
    },
    {
      kind: "category",
      name: "Speech",
      colour: "#fdcb6e",
      contents: [
        { kind: "block", type: "mars_say" },
        { kind: "block", type: "mars_say_advanced" },
        {
          kind: "block",
          type: "mars_say_value",
          inputs: {
            TEXT: {
              block: { type: "mars_gemma_ask" },
            },
          },
        },
        { kind: "block", type: "mars_set_volume" },
        { kind: "block", type: "mars_listen" },
        { kind: "block", type: "mars_play_sound" },
      ],
    },
    {
      kind: "category",
      name: "AI / Chat",
      colour: "#6c5ce7",
      contents: [
        { kind: "block", type: "mars_chat_ask" },
        { kind: "block", type: "mars_gemma_ask" },
      ],
    },
    {
      kind: "category",
      name: "Head",
      colour: "#a29bfe",
      contents: [
        { kind: "block", type: "mars_head_tilt" },
        { kind: "block", type: "mars_head_tilt_v" },
        { kind: "block", type: "mars_head_emotion" },
      ],
    },
    {
      kind: "category",
      name: "Lights",
      colour: "#e84393",
      contents: [
        { kind: "block", type: "mars_set_led_color" },
        { kind: "block", type: "mars_led_pattern" },
        { kind: "block", type: "mars_leds_off" },
      ],
    },
    {
      kind: "category",
      name: "Events",
      colour: "#6c5ce7",
      contents: [
        { kind: "block", type: "mars_when_condition" },
        { kind: "block", type: "mars_when_distance" },
        { kind: "block", type: "mars_when_tag" },
        { kind: "block", type: "mars_forever" },
        { kind: "block", type: "mars_wait_until" },
      ],
    },
    {
      kind: "category",
      name: "Utilities",
      colour: "#636e72",
      contents: [
        { kind: "block", type: "mars_run_skill" },
        { kind: "block", type: "mars_abs" },
        { kind: "block", type: "mars_random" },
        { kind: "block", type: "mars_wait" },
        {
          kind: "block",
          type: "mars_print",
          inputs: {
            VALUE: {
              block: { type: "mars_get_distance" },
            },
          },
        },
      ],
    },
    { kind: "sep" },
    {
      kind: "category",
      name: "Logic",
      colour: "#6c5ce7",
      contents: [
        { kind: "block", type: "controls_if" },
        { kind: "block", type: "controls_if", extraState: { hasElse: true } },
        { kind: "block", type: "logic_compare" },
        { kind: "block", type: "logic_operation" },
        { kind: "block", type: "logic_negate" },
        { kind: "block", type: "logic_boolean" },
      ],
    },
    {
      kind: "category",
      name: "Loops",
      colour: "#00b894",
      contents: [
        { kind: "block", type: "controls_repeat_ext" },
        { kind: "block", type: "controls_whileUntil" },
        { kind: "block", type: "controls_for" },
      ],
    },
    {
      kind: "category",
      name: "Math",
      colour: "#0984e3",
      contents: [
        { kind: "block", type: "math_number" },
        { kind: "block", type: "math_arithmetic" },
        { kind: "block", type: "math_random_int" },
      ],
    },
    {
      kind: "category",
      name: "Text",
      colour: "#0984e3",
      contents: [
        { kind: "block", type: "text" },
        { kind: "block", type: "text_join" },
        { kind: "block", type: "text_print" },
      ],
    },
    {
      kind: "category",
      name: "Variables",
      colour: "#e84393",
      custom: "VARIABLE",
    },
  ],
};
