import * as Blockly from "blockly";

const armBlocks = Blockly.common.createBlockDefinitionsFromJsonArray([
  {
    type: "mars_arm_home",
    message0: "move arm to home position",
    previousStatement: null,
    nextStatement: null,
    colour: "#e17055",
    tooltip: "Reset the arm to its default home position",
  },
  {
    type: "mars_arm_move_to",
    message0: "move arm to x %1 y %2 z %3",
    args0: [
      { type: "field_number", name: "X", value: 0 },
      { type: "field_number", name: "Y", value: 0 },
      { type: "field_number", name: "Z", value: 20 },
    ],
    previousStatement: null,
    nextStatement: null,
    colour: "#e17055",
    tooltip: "Move the arm end-effector to a position (cm)",
  },
  {
    type: "mars_arm_move_to_v",
    message0: "move arm to x %1 y %2 z %3",
    args0: [
      { type: "input_value", name: "X", check: "Number" },
      { type: "input_value", name: "Y", check: "Number" },
      { type: "input_value", name: "Z", check: "Number" },
    ],
    previousStatement: null,
    nextStatement: null,
    colour: "#e17055",
    tooltip: "Move arm — plug in variables or expressions for X, Y, Z (cm)",
  },
  {
    type: "mars_gripper",
    message0: "%1 gripper",
    args0: [
      {
        type: "field_dropdown",
        name: "ACTION",
        options: [
          ["open", "OPEN"],
          ["close", "CLOSE"],
        ],
      },
    ],
    previousStatement: null,
    nextStatement: null,
    colour: "#e17055",
    tooltip: "Open or close the robot gripper",
  },
  {
    type: "mars_wave",
    message0: "wave hello",
    previousStatement: null,
    nextStatement: null,
    colour: "#e17055",
    tooltip: "Make Mars wave its arm in greeting",
  },
  {
    type: "mars_pick_up",
    message0: "pick up object in front",
    previousStatement: null,
    nextStatement: null,
    colour: "#e17055",
    tooltip: "Attempt to pick up the nearest object",
  },
  {
    type: "mars_joint_position",
    message0: "set %1 to %2 degrees",
    args0: [
      {
        type: "field_dropdown",
        name: "JOINT",
        options: [
          ["joint 1 (base)", "1"],
          ["joint 2 (shoulder)", "2"],
          ["joint 3 (elbow)", "3"],
          ["joint 4 (wrist pitch)", "4"],
          ["joint 5 (wrist roll)", "5"],
          ["joint 6 (wrist yaw)", "6"],
        ],
      },
      { type: "field_angle", name: "ANGLE", angle: 0 },
    ],
    previousStatement: null,
    nextStatement: null,
    colour: "#e17055",
    tooltip: "Set a single arm joint to a specific angle in degrees",
  },
  {
    type: "mars_all_joints",
    message0: "set all joints %1 J1 %2 J2 %3 J3 %4 J4 %5 J5 %6 J6 %7",
    args0: [
      { type: "input_dummy" },
      { type: "field_number", name: "J1", value: 0 },
      { type: "field_number", name: "J2", value: 0 },
      { type: "field_number", name: "J3", value: 0 },
      { type: "field_number", name: "J4", value: 0 },
      { type: "field_number", name: "J5", value: 0 },
      { type: "field_number", name: "J6", value: 0 },
    ],
    previousStatement: null,
    nextStatement: null,
    colour: "#e17055",
    tooltip: "Set all 6 arm joints at once (degrees)",
  },
  {
    type: "mars_arm_torque_off",
    message0: "arm torque off (freedrive)",
    previousStatement: null,
    nextStatement: null,
    colour: "#e17055",
    tooltip: "Disable arm servo torque so you can move the arm by hand",
  },
  {
    type: "mars_arm_torque_on",
    message0: "arm torque on (lock)",
    previousStatement: null,
    nextStatement: null,
    colour: "#e17055",
    tooltip: "Re-enable arm servo torque to hold position",
  },
]);

export default armBlocks;
